name: kmeans_dominant_colors
description: A Flutter package to extract dominant colors from images using K-means clustering algorithm. Perfect for generating color palettes, theme suggestions, and image analysis.
version: 0.0.1
homepage: https://github.com/Mouhib777/kmeans_dominant_colors
repository: https://github.com/Mouhib777/kmeans_dominant_colors.git
issue_tracker: https://github.com/Mouhib777/kmeans_dominant_colors/issues
license: MIT

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  image: ^4.5.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  test: ^1.24.0

flutter:
  uses-material-design: true
# For publishing to pub.dev
